-- Funciones
use Posse;

DROP FUNCTION IF EXISTS FN_GET_VOLUME;
DELIMITER $$
CREATE FUNCTION FN_GET_VOLUME (SERIES INT, WEIGHT INT, REPS INT, UNIT ENUM('KGs', 'LBs'))
RETURNS VARCHAR(10)
DETERMINISTIC
BEGIN
	RETURN CONCAT(SERIES * WEIGHT * REPS, UNIT);
END $$ 
DELIMITER ;

DROP FUNCTION IF EXISTS FN_GET_MOVEMENT;
DELIMITER $$
CREATE FUNCTION FN_GET_MOVEMENT (movement_id INT)
RETURNS VARCHAR(20)
DETERMINISTIC
BEGIN
	DECLARE movement VARCHAR(20);
    
    SELECT Movements.movement_name INTO movement 
    FROM Posse.Exercise as Exercises
    JOIN Posse.Movements as Movements
    ON Exercises.fk_movement = Movements.pk_id
    WHERE Exercises.pk_id = movement_id;
    RETURN movement;
END $$ 
DELIMITER ;